FROM golang:bookworm

WORKDIR /app

COPY go.mod go.sum ./

# For Proxy (V2ray for iran internet :D)
RUN go env -w GOPROXY=https://package-mirror.liara.ir/repository/go/
RUN go env -w GOSUMDB=off

RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

EXPOSE 3001

CMD ["air", "-c", ".air.toml"]