apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: honarino-ingress
    namespace: honarino
spec:
    rules:
        - host:
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 3000
                  - path: /api/
                    pathType: Prefix
                    backend:
                        service:
                            name: api
                            port:
                                number: 8000
                  - path: /uploads/
                    pathType: Prefix
                    backend:
                        service:
                            name: minio
                            port:
                                number: 9000
                  - path: /pgbackweb
                    pathType: Prefix
                    backend:
                        service:
                            name: pgbackweb-service
                            port:
                                number: 8085

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: argocd-ingress-no-domain
    namespace: argocd
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
    rules:
        - http:
              paths:
                  - path: /argocd
                    pathType: Prefix
                    backend:
                        service:
                            name: argocd-server
                            port:
                                number: 80
