apiVersion: apps/v1
kind: Deployment
metadata:
    name: pgbackweb
    namespace: honarino
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pgbackweb
    template:
        metadata:
            labels:
                app: pgbackweb
        spec:
            initContainers:
                - name: create-db-if-not-exists
                  image: postgres:15
                  env:
                      - name: PGPASSWORD
                        value: postgres
                  command:
                      - sh
                      - -c
                      - |
                          until pg_isready -h postgres -p 5432; do
                            echo "Waiting for postgres..."
                            sleep 2
                          done

                          DB_EXISTS=$(psql -h postgres -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='pgbackweb'")

                          if [ "$DB_EXISTS" != "1" ]; then
                            echo "Creating database pgbackweb..."
                            psql -h postgres -U postgres -c "CREATE DATABASE pgbackweb;"
                          else
                            echo "Database already exists."
                          fi

            containers:
                - name: pgbackweb
                  image: eduardolat/pgbackweb:latest
                  ports:
                      - containerPort: 8085
                  volumeMounts:
                      - mountPath: /var/honarino/backups
                        name: backups-vol
                  envFrom:
                      - secretRef:
                            name: pgbackweb-secret

            volumes:
                - name: backups-vol
                  persistentVolumeClaim:
                      claimName: backups-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: pgbackweb-service
    namespace: honarino
spec:
    selector:
        app: pgbackweb
    ports:
        - port: 8085
          targetPort: 8085
