// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateCategory = `-- name: ActivateCategory :execrows
UPDATE categories
SET active = TRUE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ActivateCategory(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, activateCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS (
    SELECT 1 FROM categories
    WHERE id = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) CategoryExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAllCategories = `-- name: CountAllCategories :one
SELECT COUNT(*)
FROM categories c
WHERE c.deleted_at IS NULL
  AND ($1::text = '' OR c.name ILIKE '%' || $1 || '%' OR c.slug ILIKE '%' || $1 || '%')
  AND (
    $2::text = 'all' OR $2 = ''
    OR ($2 = 'active' AND c.active = TRUE)
    OR ($2 = 'inactive' AND c.active = FALSE)
  )
`

type CountAllCategoriesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAllCategories(ctx context.Context, arg CountAllCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCategories, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChildCategories = `-- name: CountChildCategories :one
SELECT COUNT(*)
FROM categories
WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountChildCategories(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildCategories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    parent_id,
    name,
    slug,
    description,
    active
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parent_id, name, slug, description, active,
          created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Active,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :execrows
UPDATE categories
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeactivateCategory(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryAncestors = `-- name: GetCategoryAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT
        c.id,
        c.parent_id,
        c.name,
        c.slug,
        c.description,
        c.active,
        0 AS depth
    FROM categories c
    WHERE c.id = $1 AND c.deleted_at IS NULL

    UNION ALL

    SELECT
        c.id,
        c.parent_id,
        c.name,
        c.slug,
        c.description,
        c.active,
        a.depth + 1
    FROM categories c
    INNER JOIN ancestors a ON c.id = a.parent_id
    WHERE c.deleted_at IS NULL
)
SELECT
    a.id,
    a.parent_id,
    a.name,
    a.slug,
    a.description,
    a.active,
    a.depth
FROM ancestors a
ORDER BY a.depth DESC
`

type GetCategoryAncestorsRow struct {
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	Depth       int32       `json:"depth"`
}

func (q *Queries) GetCategoryAncestors(ctx context.Context, id pgtype.UUID) ([]GetCategoryAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getCategoryAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryAncestorsRow
	for rows.Next() {
		var i GetCategoryAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Active,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, parent_id, name, slug, description, active,
       created_at, updated_at, deleted_at
FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, parent_id, name, slug, description, active,
       created_at, updated_at, deleted_at
FROM categories
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryDescendants = `-- name: GetCategoryDescendants :many
WITH RECURSIVE descendants AS (
    SELECT
        c.id,
        c.parent_id,
        c.name,
        c.slug,
        c.description,
        c.active,
        0 AS depth
    FROM categories c
    WHERE c.id = $1 AND c.deleted_at IS NULL

    UNION ALL

    SELECT
        c.id,
        c.parent_id,
        c.name,
        c.slug,
        c.description,
        c.active,
        d.depth + 1
    FROM categories c
    INNER JOIN descendants d ON c.parent_id = d.id
    WHERE c.deleted_at IS NULL
)
SELECT
    d.id,
    d.parent_id,
    d.name,
    d.slug,
    d.description,
    d.active,
    d.depth
FROM descendants d
WHERE d.depth > 0
ORDER BY d.depth ASC
`

type GetCategoryDescendantsRow struct {
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	Depth       int32       `json:"depth"`
}

func (q *Queries) GetCategoryDescendants(ctx context.Context, id pgtype.UUID) ([]GetCategoryDescendantsRow, error) {
	rows, err := q.db.Query(ctx, getCategoryDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryDescendantsRow
	for rows.Next() {
		var i GetCategoryDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Active,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryWithParent = `-- name: GetCategoryWithParent :one
SELECT
    c.id            AS id,
    c.name          AS name,
    c.slug          AS slug,
    c.description   AS description,
    c.active        AS active,
    c.created_at    AS created_at,
    c.updated_at    AS updated_at,

    pc.id           AS parent_id,
    pc.name         AS parent_name,
    pc.slug         AS parent_slug,
    pc.description  AS parent_description
FROM categories c
LEFT JOIN categories pc ON pc.id = c.parent_id AND pc.deleted_at IS NULL
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCategoryWithParentRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	ParentName        pgtype.Text        `json:"parent_name"`
	ParentSlug        pgtype.Text        `json:"parent_slug"`
	ParentDescription pgtype.Text        `json:"parent_description"`
}

func (q *Queries) GetCategoryWithParent(ctx context.Context, id pgtype.UUID) (GetCategoryWithParentRow, error) {
	row := q.db.QueryRow(ctx, getCategoryWithParent, id)
	var i GetCategoryWithParentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.ParentName,
		&i.ParentSlug,
		&i.ParentDescription,
	)
	return i, err
}

const hasChildren = `-- name: HasChildren :one
SELECT EXISTS (
    SELECT 1 FROM categories
    WHERE parent_id = $1 AND deleted_at IS NULL
) AS has_children
`

func (q *Queries) HasChildren(ctx context.Context, parentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasChildren, parentID)
	var has_children bool
	err := row.Scan(&has_children)
	return has_children, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT
    c.id, c.parent_id, c.name, c.slug, c.description, c.active,
    c.created_at, c.updated_at,
    pc.name AS parent_name
FROM categories c
LEFT JOIN categories pc ON pc.id = c.parent_id AND pc.deleted_at IS NULL
WHERE c.deleted_at IS NULL
  AND ($3::text = '' OR c.name ILIKE '%' || $3 || '%' OR c.slug ILIKE '%' || $3 || '%')
  AND (
    $4::text = 'all' OR $4 = ''
    OR ($4 = 'active' AND c.active = TRUE)
    OR ($4 = 'inactive' AND c.active = FALSE)
  )
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCategoriesParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

type ListAllCategoriesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ParentName  pgtype.Text        `json:"parent_name"`
}

func (q *Queries) ListAllCategories(ctx context.Context, arg ListAllCategoriesParams) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCategoriesRow
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, parent_id, name, slug, description, active,
       created_at, updated_at
FROM categories
WHERE parent_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean IS NULL OR active = $2)
ORDER BY name ASC
`

type ListChildCategoriesParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Column2  bool        `json:"column_2"`
}

type ListChildCategoriesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListChildCategories(ctx context.Context, arg ListChildCategoriesParams) ([]ListChildCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listChildCategories, arg.ParentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildCategoriesRow
	for rows.Next() {
		var i ListChildCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT id, parent_id, name, slug, description, active,
       created_at, updated_at
FROM categories
WHERE parent_id IS NULL
  AND deleted_at IS NULL
  AND ($1::boolean IS NULL OR active = $1)
ORDER BY name ASC
`

type ListRootCategoriesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRootCategories(ctx context.Context, dollar_1 bool) ([]ListRootCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listRootCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRootCategoriesRow
	for rows.Next() {
		var i ListRootCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (
    SELECT 1 FROM categories
    WHERE slug = $1 AND deleted_at IS NULL
      AND ($2::uuid IS NULL OR id != $2)
) AS exists
`

type SlugExistsParams struct {
	Slug    string      `json:"slug"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) SlugExists(ctx context.Context, arg SlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, arg.Slug, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, id)
	return err
}

const softDeleteCategoryWithChildren = `-- name: SoftDeleteCategoryWithChildren :exec
UPDATE categories SET deleted_at = NOW()
WHERE deleted_at IS NULL
  AND (id = $1 OR parent_id = $1)
`

func (q *Queries) SoftDeleteCategoryWithChildren(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCategoryWithChildren, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
    parent_id   = coalesce($1,   parent_id),
    name        = coalesce($2,        name),
    slug        = coalesce($3,        slug),
    description = coalesce($4, description),
    updated_at  = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, parent_id, name, slug, description, active,
          created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        pgtype.Text `json:"name"`
	Slug        pgtype.Text `json:"slug"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
