// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProductMediaType string

const (
	ProductMediaTypeImage ProductMediaType = "image"
	ProductMediaTypeVideo ProductMediaType = "video"
	ProductMediaType360   ProductMediaType = "360"
)

func (e *ProductMediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductMediaType(s)
	case string:
		*e = ProductMediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductMediaType: %T", src)
	}
	return nil
}

type NullProductMediaType struct {
	ProductMediaType ProductMediaType `json:"product_media_type"`
	Valid            bool             `json:"valid"` // Valid is true if ProductMediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductMediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductMediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductMediaType), nil
}

type ProductStatus string

const (
	ProductStatusActive   ProductStatus = "active"
	ProductStatusInactive ProductStatus = "inactive"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type ProductionMemberRole string

const (
	ProductionMemberRoleOwner  ProductionMemberRole = "owner"
	ProductionMemberRoleAdmin  ProductionMemberRole = "admin"
	ProductionMemberRoleEditor ProductionMemberRole = "editor"
)

func (e *ProductionMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductionMemberRole(s)
	case string:
		*e = ProductionMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductionMemberRole: %T", src)
	}
	return nil
}

type NullProductionMemberRole struct {
	ProductionMemberRole ProductionMemberRole `json:"production_member_role"`
	Valid                bool                 `json:"valid"` // Valid is true if ProductionMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductionMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProductionMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductionMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductionMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductionMemberRole), nil
}

type UserRole string

const (
	UserRoleUser   UserRole = "user"
	UserRoleVendor UserRole = "vendor"
	UserRoleAdmin  UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Product struct {
	ID                 pgtype.UUID        `json:"id"`
	ShopID             pgtype.UUID        `json:"shop_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	FromPrice          pgtype.Numeric     `json:"from_price"`
	ToPrice            pgtype.Numeric     `json:"to_price"`
	IsPriceHidden      bool               `json:"is_price_hidden"`
	Material           pgtype.Text        `json:"material"`
	Style              pgtype.Text        `json:"style"`
	Dimensions         pgtype.Text        `json:"dimensions"`
	ProductionTimeDays pgtype.Int4        `json:"production_time_days"`
	IsCustomizable     bool               `json:"is_customizable"`
	Status             ProductStatus      `json:"status"`
	ViewsCount         int32              `json:"views_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type ProductCategory struct {
	ID         pgtype.UUID        `json:"id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProductMedium struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Type      ProductMediaType   `json:"type"`
	Url       string             `json:"url"`
	SortOrder int32              `json:"sort_order"`
	AltText   pgtype.Text        `json:"alt_text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Production struct {
	ID                pgtype.UUID        `json:"id"`
	ShopID            string             `json:"shop_id"`
	ShopName          string             `json:"shop_name"`
	ShopDescription   string             `json:"shop_description"`
	ProductionAddress string             `json:"production_address"`
	ProductionPhone   string             `json:"production_phone"`
	ProductionEmail   string             `json:"production_email"`
	Telegram          pgtype.Text        `json:"telegram"`
	Rubika            pgtype.Text        `json:"rubika"`
	Eitaa             pgtype.Text        `json:"eitaa"`
	Whatsapp          pgtype.Text        `json:"whatsapp"`
	Website           pgtype.Text        `json:"website"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	BannerUrl         pgtype.Text        `json:"banner_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ProductionCategory struct {
	ID           pgtype.UUID        `json:"id"`
	ProductionID pgtype.UUID        `json:"production_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ProductionMember struct {
	ID           pgtype.UUID          `json:"id"`
	ProductionID pgtype.UUID          `json:"production_id"`
	UserID       pgtype.UUID          `json:"user_id"`
	Role         ProductionMemberRole `json:"role"`
	CreatedAt    pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz   `json:"updated_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Password          string             `json:"password"`
	Phone             pgtype.Text        `json:"phone"`
	Address           pgtype.Text        `json:"address"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Role              UserRole           `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type VendorRequest struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Fullname    string             `json:"fullname"`
	Nid         string             `json:"nid"`
	Phone       string             `json:"phone"`
	Email       string             `json:"email"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
