// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProduct = `-- name: ActivateProduct :execrows
UPDATE products
SET status = 'active', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ActivateProduct(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, activateProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addProductCategory = `-- name: AddProductCategory :exec
INSERT INTO product_categories (product_id, category_id)
VALUES ($1, $2)
ON CONFLICT (product_id, category_id) DO NOTHING
`

type AddProductCategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error {
	_, err := q.db.Exec(ctx, addProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const addProductMedia = `-- name: AddProductMedia :one
INSERT INTO product_media (
    product_id,
    type,
    url,
    sort_order,
    alt_text
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, type, url, sort_order, alt_text, created_at
`

type AddProductMediaParams struct {
	ProductID pgtype.UUID      `json:"product_id"`
	Type      ProductMediaType `json:"type"`
	Url       string           `json:"url"`
	SortOrder int32            `json:"sort_order"`
	AltText   pgtype.Text      `json:"alt_text"`
}

func (q *Queries) AddProductMedia(ctx context.Context, arg AddProductMediaParams) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, addProductMedia,
		arg.ProductID,
		arg.Type,
		arg.Url,
		arg.SortOrder,
		arg.AltText,
	)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.Url,
		&i.SortOrder,
		&i.AltText,
		&i.CreatedAt,
	)
	return i, err
}

const clearProductCategories = `-- name: ClearProductCategories :exec
DELETE FROM product_categories
WHERE product_id = $1
`

func (q *Queries) ClearProductCategories(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProductCategories, productID)
	return err
}

const countActiveProductsByCategory = `-- name: CountActiveProductsByCategory :one
SELECT COUNT(DISTINCT p.id)
FROM products p
INNER JOIN product_categories pc ON pc.product_id = p.id
WHERE pc.category_id = $1
  AND p.status = 'active'
  AND p.deleted_at IS NULL
`

func (q *Queries) CountActiveProductsByCategory(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProductsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveProductsByShop = `-- name: CountActiveProductsByShop :one
SELECT COUNT(*)
FROM products
WHERE shop_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) CountActiveProductsByShop(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProductsByShop, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProducts = `-- name: CountAllProducts :one
SELECT COUNT(*)
FROM products p
INNER JOIN productions s ON s.id = p.shop_id
WHERE p.deleted_at IS NULL
  AND ($1::text = '' OR p.title ILIKE '%' || $1 || '%' OR s.shop_name ILIKE '%' || $1 || '%')
  AND (
    $2::text = 'all' OR $2 = ''
    OR ($2 = 'active' AND p.status = 'active')
    OR ($2 = 'inactive' AND p.status = 'inactive')
  )
`

type CountAllProductsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAllProducts(ctx context.Context, arg CountAllProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProducts, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductMedia = `-- name: CountProductMedia :one
SELECT COUNT(*)
FROM product_media
WHERE product_id = $1
`

func (q *Queries) CountProductMedia(ctx context.Context, productID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductMedia, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByShop = `-- name: CountProductsByShop :one
SELECT COUNT(*)
FROM products
WHERE shop_id = $1
  AND deleted_at IS NULL
  AND (
    $2::text IS NULL
    OR status = $2::product_status
  )
`

type CountProductsByShopParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) CountProductsByShop(ctx context.Context, arg CountProductsByShopParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByShop, arg.ShopID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    shop_id,
    title,
    slug,
    description,
    from_price,
    to_price,
    is_price_hidden,
    material,
    style,
    dimensions,
    production_time_days,
    is_customizable,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, shop_id, title, slug, description,
          from_price, to_price, is_price_hidden,
          material, style, dimensions,
          production_time_days, is_customizable,
          status, views_count,
          created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	ShopID             pgtype.UUID    `json:"shop_id"`
	Title              string         `json:"title"`
	Slug               string         `json:"slug"`
	Description        string         `json:"description"`
	FromPrice          pgtype.Numeric `json:"from_price"`
	ToPrice            pgtype.Numeric `json:"to_price"`
	IsPriceHidden      bool           `json:"is_price_hidden"`
	Material           pgtype.Text    `json:"material"`
	Style              pgtype.Text    `json:"style"`
	Dimensions         pgtype.Text    `json:"dimensions"`
	ProductionTimeDays pgtype.Int4    `json:"production_time_days"`
	IsCustomizable     bool           `json:"is_customizable"`
	Status             ProductStatus  `json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ShopID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.FromPrice,
		arg.ToPrice,
		arg.IsPriceHidden,
		arg.Material,
		arg.Style,
		arg.Dimensions,
		arg.ProductionTimeDays,
		arg.IsCustomizable,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.FromPrice,
		&i.ToPrice,
		&i.IsPriceHidden,
		&i.Material,
		&i.Style,
		&i.Dimensions,
		&i.ProductionTimeDays,
		&i.IsCustomizable,
		&i.Status,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :execrows
UPDATE products
SET status = 'inactive', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeactivateProduct(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAllProductMedia = `-- name: DeleteAllProductMedia :exec
DELETE FROM product_media
WHERE product_id = $1
`

func (q *Queries) DeleteAllProductMedia(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllProductMedia, productID)
	return err
}

const deleteProductMedia = `-- name: DeleteProductMedia :exec
DELETE FROM product_media
WHERE id = $1 AND product_id = $2
`

type DeleteProductMediaParams struct {
	ID        pgtype.UUID `json:"id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) DeleteProductMedia(ctx context.Context, arg DeleteProductMediaParams) error {
	_, err := q.db.Exec(ctx, deleteProductMedia, arg.ID, arg.ProductID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, shop_id, title, slug, description,
       from_price, to_price, is_price_hidden,
       material, style, dimensions,
       production_time_days, is_customizable,
       status, views_count,
       created_at, updated_at, deleted_at
FROM products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.FromPrice,
		&i.ToPrice,
		&i.IsPriceHidden,
		&i.Material,
		&i.Style,
		&i.Dimensions,
		&i.ProductionTimeDays,
		&i.IsCustomizable,
		&i.Status,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, shop_id, title, slug, description,
       from_price, to_price, is_price_hidden,
       material, style, dimensions,
       production_time_days, is_customizable,
       status, views_count,
       created_at, updated_at, deleted_at
FROM products
WHERE shop_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetProductBySlugParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Slug   string      `json:"slug"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, arg.ShopID, arg.Slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.FromPrice,
		&i.ToPrice,
		&i.IsPriceHidden,
		&i.Material,
		&i.Style,
		&i.Dimensions,
		&i.ProductionTimeDays,
		&i.IsCustomizable,
		&i.Status,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementProductViews = `-- name: IncrementProductViews :exec
UPDATE products
SET views_count = views_count + 1
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) IncrementProductViews(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementProductViews, id)
	return err
}

const listActiveProductsByCategory = `-- name: ListActiveProductsByCategory :many
SELECT DISTINCT p.id, p.shop_id, p.title, p.slug, p.description,
       p.from_price, p.to_price, p.is_price_hidden,
       p.material, p.style, p.dimensions,
       p.production_time_days, p.is_customizable,
       p.status, p.views_count,
       p.created_at, p.updated_at
FROM products p
INNER JOIN product_categories pc ON pc.product_id = p.id
WHERE pc.category_id = $1
  AND p.status = 'active'
  AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveProductsByCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListActiveProductsByCategoryRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ShopID             pgtype.UUID        `json:"shop_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	FromPrice          pgtype.Numeric     `json:"from_price"`
	ToPrice            pgtype.Numeric     `json:"to_price"`
	IsPriceHidden      bool               `json:"is_price_hidden"`
	Material           pgtype.Text        `json:"material"`
	Style              pgtype.Text        `json:"style"`
	Dimensions         pgtype.Text        `json:"dimensions"`
	ProductionTimeDays pgtype.Int4        `json:"production_time_days"`
	IsCustomizable     bool               `json:"is_customizable"`
	Status             ProductStatus      `json:"status"`
	ViewsCount         int32              `json:"views_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveProductsByCategory(ctx context.Context, arg ListActiveProductsByCategoryParams) ([]ListActiveProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductsByCategoryRow
	for rows.Next() {
		var i ListActiveProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.FromPrice,
			&i.ToPrice,
			&i.IsPriceHidden,
			&i.Material,
			&i.Style,
			&i.Dimensions,
			&i.ProductionTimeDays,
			&i.IsCustomizable,
			&i.Status,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProductsByShop = `-- name: ListActiveProductsByShop :many
SELECT id, shop_id, title, slug, description,
       from_price, to_price, is_price_hidden,
       material, style, dimensions,
       production_time_days, is_customizable,
       status, views_count,
       created_at, updated_at
FROM products
WHERE shop_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveProductsByShopParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListActiveProductsByShopRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ShopID             pgtype.UUID        `json:"shop_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	FromPrice          pgtype.Numeric     `json:"from_price"`
	ToPrice            pgtype.Numeric     `json:"to_price"`
	IsPriceHidden      bool               `json:"is_price_hidden"`
	Material           pgtype.Text        `json:"material"`
	Style              pgtype.Text        `json:"style"`
	Dimensions         pgtype.Text        `json:"dimensions"`
	ProductionTimeDays pgtype.Int4        `json:"production_time_days"`
	IsCustomizable     bool               `json:"is_customizable"`
	Status             ProductStatus      `json:"status"`
	ViewsCount         int32              `json:"views_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveProductsByShop(ctx context.Context, arg ListActiveProductsByShopParams) ([]ListActiveProductsByShopRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductsByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductsByShopRow
	for rows.Next() {
		var i ListActiveProductsByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.FromPrice,
			&i.ToPrice,
			&i.IsPriceHidden,
			&i.Material,
			&i.Style,
			&i.Dimensions,
			&i.ProductionTimeDays,
			&i.IsCustomizable,
			&i.Status,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT p.id, p.shop_id, p.title, p.slug, p.description,
       p.from_price, p.to_price, p.is_price_hidden,
       p.material, p.style, p.dimensions,
       p.production_time_days, p.is_customizable,
       p.status, p.views_count,
       p.created_at, p.updated_at,
       s.shop_name
FROM products p
INNER JOIN productions s ON s.id = p.shop_id
WHERE p.deleted_at IS NULL
  AND ($3::text = '' OR p.title ILIKE '%' || $3 || '%' OR s.shop_name ILIKE '%' || $3 || '%')
  AND (
    $4::text = 'all' OR $4 = ''
    OR ($4 = 'active' AND p.status = 'active')
    OR ($4 = 'inactive' AND p.status = 'inactive')
  )
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllProductsParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

type ListAllProductsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ShopID             pgtype.UUID        `json:"shop_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	FromPrice          pgtype.Numeric     `json:"from_price"`
	ToPrice            pgtype.Numeric     `json:"to_price"`
	IsPriceHidden      bool               `json:"is_price_hidden"`
	Material           pgtype.Text        `json:"material"`
	Style              pgtype.Text        `json:"style"`
	Dimensions         pgtype.Text        `json:"dimensions"`
	ProductionTimeDays pgtype.Int4        `json:"production_time_days"`
	IsCustomizable     bool               `json:"is_customizable"`
	Status             ProductStatus      `json:"status"`
	ViewsCount         int32              `json:"views_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ShopName           string             `json:"shop_name"`
}

func (q *Queries) ListAllProducts(ctx context.Context, arg ListAllProductsParams) ([]ListAllProductsRow, error) {
	rows, err := q.db.Query(ctx, listAllProducts,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProductsRow
	for rows.Next() {
		var i ListAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.FromPrice,
			&i.ToPrice,
			&i.IsPriceHidden,
			&i.Material,
			&i.Style,
			&i.Dimensions,
			&i.ProductionTimeDays,
			&i.IsCustomizable,
			&i.Status,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForProducts = `-- name: ListCategoriesForProducts :many
SELECT pc.product_id, c.id, c.name, c.slug, c.parent_id
FROM product_categories pc
INNER JOIN categories c ON c.id = pc.category_id
WHERE pc.product_id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
ORDER BY c.name ASC
`

type ListCategoriesForProductsRow struct {
	ProductID pgtype.UUID `json:"product_id"`
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	ParentID  pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListCategoriesForProducts(ctx context.Context, productIds []pgtype.UUID) ([]ListCategoriesForProductsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForProducts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesForProductsRow
	for rows.Next() {
		var i ListCategoriesForProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaForProducts = `-- name: ListMediaForProducts :many
SELECT id, product_id, type, url, sort_order, alt_text, created_at
FROM product_media
WHERE product_id = ANY($1::uuid[])
ORDER BY product_id, sort_order ASC
`

func (q *Queries) ListMediaForProducts(ctx context.Context, productIds []pgtype.UUID) ([]ProductMedium, error) {
	rows, err := q.db.Query(ctx, listMediaForProducts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMedium
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Type,
			&i.Url,
			&i.SortOrder,
			&i.AltText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCategories = `-- name: ListProductCategories :many
SELECT c.id, c.name, c.slug, c.parent_id
FROM product_categories pc
INNER JOIN categories c ON c.id = pc.category_id
WHERE pc.product_id = $1 AND c.deleted_at IS NULL
ORDER BY c.name ASC
`

type ListProductCategoriesRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListProductCategories(ctx context.Context, productID pgtype.UUID) ([]ListProductCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listProductCategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductCategoriesRow
	for rows.Next() {
		var i ListProductCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductMedia = `-- name: ListProductMedia :many
SELECT id, product_id, type, url, sort_order, alt_text, created_at
FROM product_media
WHERE product_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListProductMedia(ctx context.Context, productID pgtype.UUID) ([]ProductMedium, error) {
	rows, err := q.db.Query(ctx, listProductMedia, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMedium
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Type,
			&i.Url,
			&i.SortOrder,
			&i.AltText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByShop = `-- name: ListProductsByShop :many
SELECT id, shop_id, title, slug, description,
       from_price, to_price, is_price_hidden,
       material, style, dimensions,
       production_time_days, is_customizable,
       status, views_count,
       created_at, updated_at
FROM products
WHERE shop_id = $1
  AND deleted_at IS NULL
  AND (
    $4::text IS NULL
    OR status = $4::product_status
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByShopParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
}

type ListProductsByShopRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ShopID             pgtype.UUID        `json:"shop_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	FromPrice          pgtype.Numeric     `json:"from_price"`
	ToPrice            pgtype.Numeric     `json:"to_price"`
	IsPriceHidden      bool               `json:"is_price_hidden"`
	Material           pgtype.Text        `json:"material"`
	Style              pgtype.Text        `json:"style"`
	Dimensions         pgtype.Text        `json:"dimensions"`
	ProductionTimeDays pgtype.Int4        `json:"production_time_days"`
	IsCustomizable     bool               `json:"is_customizable"`
	Status             ProductStatus      `json:"status"`
	ViewsCount         int32              `json:"views_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]ListProductsByShopRow, error) {
	rows, err := q.db.Query(ctx, listProductsByShop,
		arg.ShopID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByShopRow
	for rows.Next() {
		var i ListProductsByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.FromPrice,
			&i.ToPrice,
			&i.IsPriceHidden,
			&i.Material,
			&i.Style,
			&i.Dimensions,
			&i.ProductionTimeDays,
			&i.IsCustomizable,
			&i.Status,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS (
    SELECT 1 FROM products
    WHERE id = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) ProductExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const slugExistsForShop = `-- name: SlugExistsForShop :one
SELECT EXISTS (
    SELECT 1 FROM products
    WHERE shop_id = $1 AND slug = $2 AND deleted_at IS NULL
      AND ($3::uuid IS NULL OR id != $3)
) AS exists
`

type SlugExistsForShopParams struct {
	ShopID  pgtype.UUID `json:"shop_id"`
	Slug    string      `json:"slug"`
	Column3 pgtype.UUID `json:"column_3"`
}

func (q *Queries) SlugExistsForShop(ctx context.Context, arg SlugExistsForShopParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugExistsForShop, arg.ShopID, arg.Slug, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    title                 = coalesce($1,                 title),
    slug                  = coalesce($2,                  slug),
    description           = coalesce($3,           description),
    from_price            = coalesce($4,            from_price),
    to_price              = coalesce($5,              to_price),
    is_price_hidden       = coalesce($6,       is_price_hidden),
    material              = coalesce($7,              material),
    style                 = coalesce($8,                 style),
    dimensions            = coalesce($9,            dimensions),
    production_time_days  = coalesce($10,  production_time_days),
    is_customizable       = coalesce($11,       is_customizable),
    updated_at            = NOW()
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, shop_id, title, slug, description,
          from_price, to_price, is_price_hidden,
          material, style, dimensions,
          production_time_days, is_customizable,
          status, views_count,
          created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Title              pgtype.Text    `json:"title"`
	Slug               pgtype.Text    `json:"slug"`
	Description        pgtype.Text    `json:"description"`
	FromPrice          pgtype.Numeric `json:"from_price"`
	ToPrice            pgtype.Numeric `json:"to_price"`
	IsPriceHidden      pgtype.Bool    `json:"is_price_hidden"`
	Material           pgtype.Text    `json:"material"`
	Style              pgtype.Text    `json:"style"`
	Dimensions         pgtype.Text    `json:"dimensions"`
	ProductionTimeDays pgtype.Int4    `json:"production_time_days"`
	IsCustomizable     pgtype.Bool    `json:"is_customizable"`
	ID                 pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.FromPrice,
		arg.ToPrice,
		arg.IsPriceHidden,
		arg.Material,
		arg.Style,
		arg.Dimensions,
		arg.ProductionTimeDays,
		arg.IsCustomizable,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.FromPrice,
		&i.ToPrice,
		&i.IsPriceHidden,
		&i.Material,
		&i.Style,
		&i.Dimensions,
		&i.ProductionTimeDays,
		&i.IsCustomizable,
		&i.Status,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductMediaSortOrder = `-- name: UpdateProductMediaSortOrder :exec
UPDATE product_media
SET sort_order = $2
WHERE id = $1
`

type UpdateProductMediaSortOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateProductMediaSortOrder(ctx context.Context, arg UpdateProductMediaSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateProductMediaSortOrder, arg.ID, arg.SortOrder)
	return err
}
