// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductionCategory = `-- name: AddProductionCategory :exec
INSERT INTO production_categories (production_id, category_id)
VALUES ($1, $2)
ON CONFLICT (production_id, category_id) DO NOTHING
`

type AddProductionCategoryParams struct {
	ProductionID pgtype.UUID `json:"production_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
}

func (q *Queries) AddProductionCategory(ctx context.Context, arg AddProductionCategoryParams) error {
	_, err := q.db.Exec(ctx, addProductionCategory, arg.ProductionID, arg.CategoryID)
	return err
}

const clearProductionCategories = `-- name: ClearProductionCategories :exec
DELETE FROM production_categories
WHERE production_id = $1
`

func (q *Queries) ClearProductionCategories(ctx context.Context, productionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProductionCategories, productionID)
	return err
}

const countActiveProductionsByCategory = `-- name: CountActiveProductionsByCategory :one
SELECT COUNT(*)
FROM production_categories pc
INNER JOIN productions p ON p.id = pc.production_id
WHERE pc.category_id = $1
  AND p.active = TRUE
  AND p.deleted_at IS NULL
`

func (q *Queries) CountActiveProductionsByCategory(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProductionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveProductionsByCategory = `-- name: ListActiveProductionsByCategory :many
SELECT p.id, p.shop_id, p.shop_name, p.shop_description,
       p.production_address, p.production_phone, p.production_email,
       p.telegram, p.rubika, p.eitaa, p.whatsapp, p.website,
       p.logo_url, p.banner_url, p.cover_url,
       p.active, p.created_at, p.updated_at
FROM production_categories pc
INNER JOIN productions p ON p.id = pc.production_id
WHERE pc.category_id = $1
  AND p.active = TRUE
  AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveProductionsByCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListActiveProductionsByCategoryRow struct {
	ID                pgtype.UUID        `json:"id"`
	ShopID            string             `json:"shop_id"`
	ShopName          string             `json:"shop_name"`
	ShopDescription   string             `json:"shop_description"`
	ProductionAddress string             `json:"production_address"`
	ProductionPhone   string             `json:"production_phone"`
	ProductionEmail   string             `json:"production_email"`
	Telegram          pgtype.Text        `json:"telegram"`
	Rubika            pgtype.Text        `json:"rubika"`
	Eitaa             pgtype.Text        `json:"eitaa"`
	Whatsapp          pgtype.Text        `json:"whatsapp"`
	Website           pgtype.Text        `json:"website"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	BannerUrl         pgtype.Text        `json:"banner_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveProductionsByCategory(ctx context.Context, arg ListActiveProductionsByCategoryParams) ([]ListActiveProductionsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductionsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductionsByCategoryRow
	for rows.Next() {
		var i ListActiveProductionsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ShopName,
			&i.ShopDescription,
			&i.ProductionAddress,
			&i.ProductionPhone,
			&i.ProductionEmail,
			&i.Telegram,
			&i.Rubika,
			&i.Eitaa,
			&i.Whatsapp,
			&i.Website,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.CoverUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForProductions = `-- name: ListCategoriesForProductions :many
SELECT pc.production_id, c.id, c.name, c.slug, c.parent_id
FROM production_categories pc
INNER JOIN categories c ON c.id = pc.category_id
WHERE pc.production_id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
ORDER BY c.name ASC
`

type ListCategoriesForProductionsRow struct {
	ProductionID pgtype.UUID `json:"production_id"`
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	ParentID     pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListCategoriesForProductions(ctx context.Context, productionIds []pgtype.UUID) ([]ListCategoriesForProductionsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForProductions, productionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesForProductionsRow
	for rows.Next() {
		var i ListCategoriesForProductionsRow
		if err := rows.Scan(
			&i.ProductionID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionCategories = `-- name: ListProductionCategories :many
SELECT c.id, c.name, c.slug, c.parent_id
FROM production_categories pc
INNER JOIN categories c ON c.id = pc.category_id
WHERE pc.production_id = $1 AND c.deleted_at IS NULL
ORDER BY c.name ASC
`

type ListProductionCategoriesRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListProductionCategories(ctx context.Context, productionID pgtype.UUID) ([]ListProductionCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listProductionCategories, productionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionCategoriesRow
	for rows.Next() {
		var i ListProductionCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
