// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: productions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProduction = `-- name: ActivateProduction :execrows
UPDATE productions
SET active = TRUE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ActivateProduction(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, activateProduction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addProductionMember = `-- name: AddProductionMember :one
INSERT INTO production_members (production_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, production_id, user_id, role, created_at, updated_at
`

type AddProductionMemberParams struct {
	ProductionID pgtype.UUID          `json:"production_id"`
	UserID       pgtype.UUID          `json:"user_id"`
	Role         ProductionMemberRole `json:"role"`
}

func (q *Queries) AddProductionMember(ctx context.Context, arg AddProductionMemberParams) (ProductionMember, error) {
	row := q.db.QueryRow(ctx, addProductionMember, arg.ProductionID, arg.UserID, arg.Role)
	var i ProductionMember
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAllProductions = `-- name: CountAllProductions :one
SELECT COUNT(*)
FROM productions p
INNER JOIN production_members pm
    ON pm.production_id = p.id AND pm.role = 'owner'
INNER JOIN users u
    ON u.id = pm.user_id
WHERE p.deleted_at IS NULL
  AND ($1::text = '' OR p.shop_name ILIKE '%' || $1 || '%' OR u.name ILIKE '%' || $1 || '%' OR p.production_phone ILIKE '%' || $1 || '%')
  AND (
    $2::text = 'all' OR $2 = ''
    OR ($2 = 'active' AND p.active = TRUE)
    OR ($2 = 'inactive' AND p.active = FALSE)
  )
`

type CountAllProductionsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAllProductions(ctx context.Context, arg CountAllProductionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProductions, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductionMembers = `-- name: CountProductionMembers :one
SELECT COUNT(*)
FROM production_members
WHERE production_id = $1
`

func (q *Queries) CountProductionMembers(ctx context.Context, productionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductionMembers, productionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductionsByUserID = `-- name: CountProductionsByUserID :one
SELECT COUNT(*)
FROM productions p
INNER JOIN production_members pm ON pm.production_id = p.id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) CountProductionsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductionsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduction = `-- name: CreateProduction :one
INSERT INTO productions (
    shop_id,
    shop_name,
    shop_description,
    production_address,
    production_phone,
    production_email,
    telegram,
    rubika,
    eitaa,
    whatsapp,
    website,
    active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, shop_id, shop_name, shop_description,
          production_address, production_phone, production_email,
          telegram, rubika, eitaa, whatsapp, website,
          logo_url, banner_url, cover_url,
          active,
          created_at, updated_at, deleted_at
`

type CreateProductionParams struct {
	ShopID            string      `json:"shop_id"`
	ShopName          string      `json:"shop_name"`
	ShopDescription   string      `json:"shop_description"`
	ProductionAddress string      `json:"production_address"`
	ProductionPhone   string      `json:"production_phone"`
	ProductionEmail   string      `json:"production_email"`
	Telegram          pgtype.Text `json:"telegram"`
	Rubika            pgtype.Text `json:"rubika"`
	Eitaa             pgtype.Text `json:"eitaa"`
	Whatsapp          pgtype.Text `json:"whatsapp"`
	Website           pgtype.Text `json:"website"`
	Active            bool        `json:"active"`
}

func (q *Queries) CreateProduction(ctx context.Context, arg CreateProductionParams) (Production, error) {
	row := q.db.QueryRow(ctx, createProduction,
		arg.ShopID,
		arg.ShopName,
		arg.ShopDescription,
		arg.ProductionAddress,
		arg.ProductionPhone,
		arg.ProductionEmail,
		arg.Telegram,
		arg.Rubika,
		arg.Eitaa,
		arg.Whatsapp,
		arg.Website,
		arg.Active,
	)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ShopName,
		&i.ShopDescription,
		&i.ProductionAddress,
		&i.ProductionPhone,
		&i.ProductionEmail,
		&i.Telegram,
		&i.Rubika,
		&i.Eitaa,
		&i.Whatsapp,
		&i.Website,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CoverUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateProduction = `-- name: DeactivateProduction :execrows
UPDATE productions
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeactivateProduction(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateProduction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembersCount = `-- name: GetMembersCount :one
SELECT
    COUNT(*) FILTER (WHERE role = 'editor') AS "EditorTotal",
    COUNT(*) FILTER (WHERE role = 'admin') AS "AdminTotal"
FROM production_members
WHERE production_id = $1
`

type GetMembersCountRow struct {
	EditorTotal int64 `json:"EditorTotal"`
	AdminTotal  int64 `json:"AdminTotal"`
}

func (q *Queries) GetMembersCount(ctx context.Context, productionID pgtype.UUID) (GetMembersCountRow, error) {
	row := q.db.QueryRow(ctx, getMembersCount, productionID)
	var i GetMembersCountRow
	err := row.Scan(&i.EditorTotal, &i.AdminTotal)
	return i, err
}

const getProductionByID = `-- name: GetProductionByID :one
SELECT id, shop_id, shop_name, shop_description,
       production_address, production_phone, production_email,
       telegram, rubika, eitaa, whatsapp, website,
       logo_url, banner_url, cover_url,
       active,
       created_at, updated_at, deleted_at
FROM productions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductionByID(ctx context.Context, id pgtype.UUID) (Production, error) {
	row := q.db.QueryRow(ctx, getProductionByID, id)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ShopName,
		&i.ShopDescription,
		&i.ProductionAddress,
		&i.ProductionPhone,
		&i.ProductionEmail,
		&i.Telegram,
		&i.Rubika,
		&i.Eitaa,
		&i.Whatsapp,
		&i.Website,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CoverUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductionBySlug = `-- name: GetProductionBySlug :one
SELECT id, shop_id, shop_name, shop_description,
       production_address, production_phone, production_email,
       telegram, rubika, eitaa, whatsapp, website,
       logo_url, banner_url, cover_url,
       active,
       created_at, updated_at, deleted_at
FROM productions
WHERE shop_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductionBySlug(ctx context.Context, shopID string) (Production, error) {
	row := q.db.QueryRow(ctx, getProductionBySlug, shopID)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ShopName,
		&i.ShopDescription,
		&i.ProductionAddress,
		&i.ProductionPhone,
		&i.ProductionEmail,
		&i.Telegram,
		&i.Rubika,
		&i.Eitaa,
		&i.Whatsapp,
		&i.Website,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CoverUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductionMember = `-- name: GetProductionMember :one
SELECT id, production_id, user_id, role, created_at, updated_at
FROM production_members
WHERE production_id = $1 AND user_id = $2
`

type GetProductionMemberParams struct {
	ProductionID pgtype.UUID `json:"production_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProductionMember(ctx context.Context, arg GetProductionMemberParams) (ProductionMember, error) {
	row := q.db.QueryRow(ctx, getProductionMember, arg.ProductionID, arg.UserID)
	var i ProductionMember
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductionOwner = `-- name: GetProductionOwner :one
SELECT pm.id, pm.user_id, pm.role, pm.created_at, pm.updated_at,
       u.name, u.username, u.email
FROM production_members pm
INNER JOIN users u ON u.id = pm.user_id
WHERE pm.production_id = $1 AND pm.role = 'owner'
`

type GetProductionOwnerRow struct {
	ID        pgtype.UUID          `json:"id"`
	UserID    pgtype.UUID          `json:"user_id"`
	Role      ProductionMemberRole `json:"role"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt pgtype.Timestamptz   `json:"updated_at"`
	Name      string               `json:"name"`
	Username  string               `json:"username"`
	Email     string               `json:"email"`
}

func (q *Queries) GetProductionOwner(ctx context.Context, productionID pgtype.UUID) (GetProductionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getProductionOwner, productionID)
	var i GetProductionOwnerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getProductionWithActiveStatus = `-- name: GetProductionWithActiveStatus :one
SELECT id, shop_id, shop_name, active
FROM productions
WHERE id = $1 AND deleted_at IS NULL
`

type GetProductionWithActiveStatusRow struct {
	ID       pgtype.UUID `json:"id"`
	ShopID   string      `json:"shop_id"`
	ShopName string      `json:"shop_name"`
	Active   bool        `json:"active"`
}

func (q *Queries) GetProductionWithActiveStatus(ctx context.Context, id pgtype.UUID) (GetProductionWithActiveStatusRow, error) {
	row := q.db.QueryRow(ctx, getProductionWithActiveStatus, id)
	var i GetProductionWithActiveStatusRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ShopName,
		&i.Active,
	)
	return i, err
}

const hasProductionRole = `-- name: HasProductionRole :one
SELECT EXISTS (
    SELECT 1 FROM production_members
    WHERE production_id = $1 AND user_id = $2 AND role = $3
) AS has_role
`

type HasProductionRoleParams struct {
	ProductionID pgtype.UUID          `json:"production_id"`
	UserID       pgtype.UUID          `json:"user_id"`
	Role         ProductionMemberRole `json:"role"`
}

func (q *Queries) HasProductionRole(ctx context.Context, arg HasProductionRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasProductionRole, arg.ProductionID, arg.UserID, arg.Role)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const isProductionActive = `-- name: IsProductionActive :one
SELECT active
FROM productions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) IsProductionActive(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isProductionActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const isProductionMember = `-- name: IsProductionMember :one
SELECT EXISTS (
    SELECT 1 FROM production_members
    WHERE production_id = $1 AND user_id = $2
) AS is_member
`

type IsProductionMemberParams struct {
	ProductionID pgtype.UUID `json:"production_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsProductionMember(ctx context.Context, arg IsProductionMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProductionMember, arg.ProductionID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listAllProductions = `-- name: ListAllProductions :many
SELECT p.id,
       p.shop_id,
       p.shop_name,
       p.shop_description,
       p.production_address,
       p.production_phone,
       p.production_email,
       p.telegram,
       p.rubika,
       p.eitaa,
       p.whatsapp,
       p.website,
       p.logo_url,
       p.banner_url,
       p.cover_url,
       p.active,
       p.created_at,
       p.updated_at,
       u.id   AS owner_id,
       u.name AS owner_name,
       u.username AS owner_username,
       u.email AS owner_email
FROM productions p
INNER JOIN production_members pm
    ON pm.production_id = p.id AND pm.role = 'owner'
INNER JOIN users u
    ON u.id = pm.user_id
WHERE p.deleted_at IS NULL
  AND ($3::text = '' OR p.shop_name ILIKE '%' || $3 || '%' OR u.name ILIKE '%' || $3 || '%' OR p.production_phone ILIKE '%' || $3 || '%')
  AND (
    $4::text = 'all' OR $4 = ''
    OR ($4 = 'active' AND p.active = TRUE)
    OR ($4 = 'inactive' AND p.active = FALSE)
  )
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllProductionsParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

type ListAllProductionsRow struct {
	ID                pgtype.UUID        `json:"id"`
	ShopID            string             `json:"shop_id"`
	ShopName          string             `json:"shop_name"`
	ShopDescription   string             `json:"shop_description"`
	ProductionAddress string             `json:"production_address"`
	ProductionPhone   string             `json:"production_phone"`
	ProductionEmail   string             `json:"production_email"`
	Telegram          pgtype.Text        `json:"telegram"`
	Rubika            pgtype.Text        `json:"rubika"`
	Eitaa             pgtype.Text        `json:"eitaa"`
	Whatsapp          pgtype.Text        `json:"whatsapp"`
	Website           pgtype.Text        `json:"website"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	BannerUrl         pgtype.Text        `json:"banner_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	OwnerName         string             `json:"owner_name"`
	OwnerUsername     string             `json:"owner_username"`
	OwnerEmail        string             `json:"owner_email"`
}

func (q *Queries) ListAllProductions(ctx context.Context, arg ListAllProductionsParams) ([]ListAllProductionsRow, error) {
	rows, err := q.db.Query(ctx, listAllProductions,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProductionsRow
	for rows.Next() {
		var i ListAllProductionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ShopName,
			&i.ShopDescription,
			&i.ProductionAddress,
			&i.ProductionPhone,
			&i.ProductionEmail,
			&i.Telegram,
			&i.Rubika,
			&i.Eitaa,
			&i.Whatsapp,
			&i.Website,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.CoverUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerUsername,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionMembers = `-- name: ListProductionMembers :many
SELECT pm.id, pm.production_id, pm.user_id, pm.role, pm.created_at, pm.updated_at,
       u.name, u.username, u.email, u.phone, u.profile_picture_url
FROM production_members pm
INNER JOIN users u ON u.id = pm.user_id
WHERE pm.production_id = $1
ORDER BY pm.created_at ASC
LIMIT $2 OFFSET $3
`

type ListProductionMembersParams struct {
	ProductionID pgtype.UUID `json:"production_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListProductionMembersRow struct {
	ID                pgtype.UUID          `json:"id"`
	ProductionID      pgtype.UUID          `json:"production_id"`
	UserID            pgtype.UUID          `json:"user_id"`
	Role              ProductionMemberRole `json:"role"`
	CreatedAt         pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz   `json:"updated_at"`
	Name              string               `json:"name"`
	Username          string               `json:"username"`
	Email             string               `json:"email"`
	Phone             pgtype.Text          `json:"phone"`
	ProfilePictureUrl pgtype.Text          `json:"profile_picture_url"`
}

func (q *Queries) ListProductionMembers(ctx context.Context, arg ListProductionMembersParams) ([]ListProductionMembersRow, error) {
	rows, err := q.db.Query(ctx, listProductionMembers, arg.ProductionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionMembersRow
	for rows.Next() {
		var i ListProductionMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.ProfilePictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionsByUserID = `-- name: ListProductionsByUserID :many
SELECT p.id,
       p.shop_id,
       p.shop_name,
       p.shop_description,
       p.production_address,
       p.production_phone,
       p.production_email,
       p.telegram,
       p.rubika,
       p.eitaa,
       p.whatsapp,
       p.website,
       p.logo_url,
       p.banner_url,
       p.cover_url,
       p.active,
       p.created_at,
       p.updated_at,
       pm.role AS member_role
FROM productions p
INNER JOIN production_members pm ON pm.production_id = p.id
WHERE pm.user_id = $1
  AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductionsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListProductionsByUserIDRow struct {
	ID                pgtype.UUID          `json:"id"`
	ShopID            string               `json:"shop_id"`
	ShopName          string               `json:"shop_name"`
	ShopDescription   string               `json:"shop_description"`
	ProductionAddress string               `json:"production_address"`
	ProductionPhone   string               `json:"production_phone"`
	ProductionEmail   string               `json:"production_email"`
	Telegram          pgtype.Text          `json:"telegram"`
	Rubika            pgtype.Text          `json:"rubika"`
	Eitaa             pgtype.Text          `json:"eitaa"`
	Whatsapp          pgtype.Text          `json:"whatsapp"`
	Website           pgtype.Text          `json:"website"`
	LogoUrl           pgtype.Text          `json:"logo_url"`
	BannerUrl         pgtype.Text          `json:"banner_url"`
	CoverUrl          pgtype.Text          `json:"cover_url"`
	Active            bool                 `json:"active"`
	CreatedAt         pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz   `json:"updated_at"`
	MemberRole        ProductionMemberRole `json:"member_role"`
}

func (q *Queries) ListProductionsByUserID(ctx context.Context, arg ListProductionsByUserIDParams) ([]ListProductionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listProductionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionsByUserIDRow
	for rows.Next() {
		var i ListProductionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ShopName,
			&i.ShopDescription,
			&i.ProductionAddress,
			&i.ProductionPhone,
			&i.ProductionEmail,
			&i.Telegram,
			&i.Rubika,
			&i.Eitaa,
			&i.Whatsapp,
			&i.Website,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.CoverUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductionMember = `-- name: RemoveProductionMember :exec
DELETE FROM production_members
WHERE production_id = $1 AND user_id = $2 AND role != 'owner'
`

type RemoveProductionMemberParams struct {
	ProductionID pgtype.UUID `json:"production_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveProductionMember(ctx context.Context, arg RemoveProductionMemberParams) error {
	_, err := q.db.Exec(ctx, removeProductionMember, arg.ProductionID, arg.UserID)
	return err
}

const searchUsersForMembership = `-- name: SearchUsersForMembership :many
SELECT u.id, u.name, u.username, u.email, u.phone, u.profile_picture_url, u.role
FROM users u
WHERE u.deleted_at IS NULL
  AND u.id <> ALL (SELECT pm.user_id FROM production_members pm WHERE pm.production_id = $1)
  AND (
    lower(u.name) LIKE '%' || lower($2) || '%'
    OR lower(u.username) LIKE '%' || lower($2) || '%'
    OR replace(u.phone, ' ', '') LIKE '%' || replace($2, ' ', '') || '%'
    OR lower(u.email) LIKE '%' || lower($2) || '%'
  )
ORDER BY u.created_at DESC
LIMIT $3
`

type SearchUsersForMembershipParams struct {
	ProductionID pgtype.UUID `json:"production_id"`
	Lower        string      `json:"lower"`
	Limit        int32       `json:"limit"`
}

type SearchUsersForMembershipRow struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	Phone             pgtype.Text `json:"phone"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	Role              UserRole    `json:"role"`
}

func (q *Queries) SearchUsersForMembership(ctx context.Context, arg SearchUsersForMembershipParams) ([]SearchUsersForMembershipRow, error) {
	rows, err := q.db.Query(ctx, searchUsersForMembership, arg.ProductionID, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersForMembershipRow
	for rows.Next() {
		var i SearchUsersForMembershipRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.ProfilePictureUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduction = `-- name: SoftDeleteProduction :exec
UPDATE productions SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduction, id)
	return err
}

const updateProduction = `-- name: UpdateProduction :one
UPDATE productions SET
    shop_id            = coalesce($1,            shop_id),
    shop_name          = coalesce($2,          shop_name),
    shop_description   = coalesce($3,   shop_description),
    production_address = coalesce($4, production_address),
    production_phone   = coalesce($5,   production_phone),
    production_email   = coalesce($6,   production_email),
    telegram           = coalesce($7,           telegram),
    rubika             = coalesce($8,             rubika),
    eitaa              = coalesce($9,              eitaa),
    whatsapp           = coalesce($10,           whatsapp),
    website            = coalesce($11,            website),
    updated_at         = NOW()
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, shop_id, shop_name, shop_description,
          production_address, production_phone, production_email,
          telegram, rubika, eitaa, whatsapp, website,
          logo_url, banner_url, cover_url,
          created_at, updated_at, deleted_at
`

type UpdateProductionParams struct {
	ShopID            pgtype.Text `json:"shop_id"`
	ShopName          pgtype.Text `json:"shop_name"`
	ShopDescription   pgtype.Text `json:"shop_description"`
	ProductionAddress pgtype.Text `json:"production_address"`
	ProductionPhone   pgtype.Text `json:"production_phone"`
	ProductionEmail   pgtype.Text `json:"production_email"`
	Telegram          pgtype.Text `json:"telegram"`
	Rubika            pgtype.Text `json:"rubika"`
	Eitaa             pgtype.Text `json:"eitaa"`
	Whatsapp          pgtype.Text `json:"whatsapp"`
	Website           pgtype.Text `json:"website"`
	ID                pgtype.UUID `json:"id"`
}

type UpdateProductionRow struct {
	ID                pgtype.UUID        `json:"id"`
	ShopID            string             `json:"shop_id"`
	ShopName          string             `json:"shop_name"`
	ShopDescription   string             `json:"shop_description"`
	ProductionAddress string             `json:"production_address"`
	ProductionPhone   string             `json:"production_phone"`
	ProductionEmail   string             `json:"production_email"`
	Telegram          pgtype.Text        `json:"telegram"`
	Rubika            pgtype.Text        `json:"rubika"`
	Eitaa             pgtype.Text        `json:"eitaa"`
	Whatsapp          pgtype.Text        `json:"whatsapp"`
	Website           pgtype.Text        `json:"website"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	BannerUrl         pgtype.Text        `json:"banner_url"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateProduction(ctx context.Context, arg UpdateProductionParams) (UpdateProductionRow, error) {
	row := q.db.QueryRow(ctx, updateProduction,
		arg.ShopID,
		arg.ShopName,
		arg.ShopDescription,
		arg.ProductionAddress,
		arg.ProductionPhone,
		arg.ProductionEmail,
		arg.Telegram,
		arg.Rubika,
		arg.Eitaa,
		arg.Whatsapp,
		arg.Website,
		arg.ID,
	)
	var i UpdateProductionRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ShopName,
		&i.ShopDescription,
		&i.ProductionAddress,
		&i.ProductionPhone,
		&i.ProductionEmail,
		&i.Telegram,
		&i.Rubika,
		&i.Eitaa,
		&i.Whatsapp,
		&i.Website,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CoverUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductionMediaURL = `-- name: UpdateProductionMediaURL :one
UPDATE productions SET
    logo_url   = CASE WHEN $1::text   IS NOT NULL THEN $1   ELSE logo_url   END,
    banner_url = CASE WHEN $2::text IS NOT NULL THEN $2 ELSE banner_url END,
    cover_url  = CASE WHEN $3::text  IS NOT NULL THEN $3  ELSE cover_url  END,
    updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, shop_id, logo_url, banner_url, cover_url, active, updated_at
`

type UpdateProductionMediaURLParams struct {
	LogoUrl   pgtype.Text `json:"logo_url"`
	BannerUrl pgtype.Text `json:"banner_url"`
	CoverUrl  pgtype.Text `json:"cover_url"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateProductionMediaURLRow struct {
	ID        pgtype.UUID        `json:"id"`
	ShopID    string             `json:"shop_id"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	BannerUrl pgtype.Text        `json:"banner_url"`
	CoverUrl  pgtype.Text        `json:"cover_url"`
	Active    bool               `json:"active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProductionMediaURL(ctx context.Context, arg UpdateProductionMediaURLParams) (UpdateProductionMediaURLRow, error) {
	row := q.db.QueryRow(ctx, updateProductionMediaURL,
		arg.LogoUrl,
		arg.BannerUrl,
		arg.CoverUrl,
		arg.ID,
	)
	var i UpdateProductionMediaURLRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CoverUrl,
		&i.Active,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductionMemberRole = `-- name: UpdateProductionMemberRole :exec
UPDATE production_members SET
    role       = $3,
    updated_at = NOW()
WHERE production_id = $1 AND user_id = $2
`

type UpdateProductionMemberRoleParams struct {
	ProductionID pgtype.UUID          `json:"production_id"`
	UserID       pgtype.UUID          `json:"user_id"`
	Role         ProductionMemberRole `json:"role"`
}

func (q *Queries) UpdateProductionMemberRole(ctx context.Context, arg UpdateProductionMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProductionMemberRole, arg.ProductionID, arg.UserID, arg.Role)
	return err
}
