// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, email, password)
VALUES ($1, $2, $3, $4)
RETURNING id, name, username, email, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Address           pgtype.Text        `json:"address"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Role              UserRole           `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPasswordByID = `-- name: GetPasswordByID :one
SELECT password FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPasswordByID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordByID, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, username, email, password, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Address           pgtype.Text        `json:"address"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Role              UserRole           `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email, password, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, username, email, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Address           pgtype.Text        `json:"address"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Role              UserRole           `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.ProfilePictureUrl,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, name, username, email, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
FROM users
WHERE role = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByRoleParams struct {
	Role   UserRole `json:"role"`
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
}

type ListUsersByRoleRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Address           pgtype.Text        `json:"address"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Role              UserRole           `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]ListUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByRoleRow
	for rows.Next() {
		var i ListUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.ProfilePictureUrl,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET
    password   = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePasswordParams struct {
	ID       pgtype.UUID `json:"id"`
	Password string      `json:"password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.Password)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name                = coalesce($1,                name),
    phone               = coalesce($2,               phone),
    address             = coalesce($3,             address),
    profile_picture_url = coalesce($4, profile_picture_url),
    updated_at          = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, name, username, email, phone, address, profile_picture_url, role, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Name              pgtype.Text `json:"name"`
	Phone             pgtype.Text `json:"phone"`
	Address           pgtype.Text `json:"address"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	ID                pgtype.UUID `json:"id"`
}

type UpdateUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Address           pgtype.Text        `json:"address"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Role              UserRole           `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.ProfilePictureUrl,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET
    role       = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role UserRole    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
