// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendor_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVendorRequests = `-- name: CountVendorRequests :one
SELECT COUNT(*) FROM vendor_requests
WHERE deleted_at IS NULL
  AND (
    NULLIF(TRIM($1::text), '') IS NULL
    OR fullname ILIKE '%' || TRIM($1::text) || '%'
    OR nid LIKE '%' || TRIM($1::text) || '%'
    OR phone LIKE '%' || TRIM($1::text) || '%'
  )
`

func (q *Queries) CountVendorRequests(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorRequests, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorRequest = `-- name: CreateVendorRequest :one
INSERT INTO vendor_requests (user_id, fullname, nid, phone, email, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, fullname, nid, phone, email, description, created_at, updated_at, deleted_at
`

type CreateVendorRequestParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Fullname    string      `json:"fullname"`
	Nid         string      `json:"nid"`
	Phone       string      `json:"phone"`
	Email       string      `json:"email"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateVendorRequest(ctx context.Context, arg CreateVendorRequestParams) (VendorRequest, error) {
	row := q.db.QueryRow(ctx, createVendorRequest,
		arg.UserID,
		arg.Fullname,
		arg.Nid,
		arg.Phone,
		arg.Email,
		arg.Description,
	)
	var i VendorRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Nid,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVendorRequestByID = `-- name: GetVendorRequestByID :one
SELECT id, user_id, fullname, nid, phone, email, description, created_at, updated_at, deleted_at
FROM vendor_requests
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVendorRequestByID(ctx context.Context, id pgtype.UUID) (VendorRequest, error) {
	row := q.db.QueryRow(ctx, getVendorRequestByID, id)
	var i VendorRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Nid,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVendorRequestByNID = `-- name: GetVendorRequestByNID :one
SELECT id, user_id, fullname, nid, phone, email, description, created_at, updated_at, deleted_at
FROM vendor_requests
WHERE nid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVendorRequestByNID(ctx context.Context, nid string) (VendorRequest, error) {
	row := q.db.QueryRow(ctx, getVendorRequestByNID, nid)
	var i VendorRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Nid,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVendorRequestByUserID = `-- name: GetVendorRequestByUserID :one
SELECT id, user_id, fullname, nid, phone, email, description, created_at, updated_at, deleted_at
FROM vendor_requests
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVendorRequestByUserID(ctx context.Context, userID pgtype.UUID) (VendorRequest, error) {
	row := q.db.QueryRow(ctx, getVendorRequestByUserID, userID)
	var i VendorRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Nid,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVendorRequests = `-- name: ListVendorRequests :many
SELECT id, user_id, fullname, nid, phone, email, description, created_at, updated_at, deleted_at
FROM vendor_requests
WHERE deleted_at IS NULL
  AND (
    NULLIF(TRIM($3::text), '') IS NULL
    OR fullname ILIKE '%' || TRIM($3::text) || '%'
    OR nid LIKE '%' || TRIM($3::text) || '%'
    OR phone LIKE '%' || TRIM($3::text) || '%'
  )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVendorRequestsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListVendorRequests(ctx context.Context, arg ListVendorRequestsParams) ([]VendorRequest, error) {
	rows, err := q.db.Query(ctx, listVendorRequests, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorRequest
	for rows.Next() {
		var i VendorRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Fullname,
			&i.Nid,
			&i.Phone,
			&i.Email,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVendorRequest = `-- name: SoftDeleteVendorRequest :exec
UPDATE vendor_requests SET
    deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVendorRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVendorRequest, id)
	return err
}

const updateVendorRequest = `-- name: UpdateVendorRequest :one
UPDATE vendor_requests SET
    fullname    = coalesce($1,    fullname),
    phone       = coalesce($2,       phone),
    email       = coalesce($3,       email),
    description = coalesce($4, description),
    updated_at  = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, user_id, fullname, nid, phone, email, description, created_at, updated_at, deleted_at
`

type UpdateVendorRequestParams struct {
	Fullname    pgtype.Text `json:"fullname"`
	Phone       pgtype.Text `json:"phone"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateVendorRequest(ctx context.Context, arg UpdateVendorRequestParams) (VendorRequest, error) {
	row := q.db.QueryRow(ctx, updateVendorRequest,
		arg.Fullname,
		arg.Phone,
		arg.Email,
		arg.Description,
		arg.ID,
	)
	var i VendorRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Nid,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
