apiVersion: v1
kind: Secret
metadata:
    name: pgbackweb-secret
    namespace: honarino
type: Opaque
stringData:
    PBW_LISTEN_ADDR: 0.0.0.0:8085
    PBW_ENCRYPTION_KEY: your-strong-32-char-secret-key-here
    PBW_POSTGRES_CONN_STRING: postgresql://postgres:postgres@postgres:5432/api_db?sslmode=disable
