# backups-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: backups-pv
spec:
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-backup
    local:
        path: /var/backups
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - tg-44849

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: backups-pvc
    namespace: honarino
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: local-backup
