name: Download files from GTA5-mods

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "*.rar"
          git lfs track "*.zip"

      - name: Download files
        run: |
          mkdir -p data

          curl -L "https://files.gta5-mods.com/uploads/fib-fbi-tower-sign-reworked-v1-0/f1ac72-FIB-FBI%20&%20CIA%20Reworked%20V2.5.rar" -o data/FIB-FBI-CIA-Reworked-V2.5.rar
          curl -L "https://files.gta5-mods.com/uploads/mapeditor-2-ymap-converter/440c88-ME2YM.zip" -o data/ME2YM.zip
          curl -L "https://files.gta5-mods.com/uploads/jantsuu-tower-add-on-sp/30965e-JANTSUU_Tower_1.0.1.zip" -o data/JANTSUU_Tower_1.0.1.zip
          curl -L "https://files.gta5-mods.com/uploads/stark-mansion/d5d1bc-Star%20Mansion%20v2.rar" -o data/Star_Mansion_v2.rar
          curl -L "https://files.gta5-mods.com/uploads/mlo-pump-run-gym-add-on-sp-fivem-ragemp/6b5674-LOKAS_GYM.rar" -o data/LOKAS_GYM.rar
          curl -L "https://files.gta5-mods.com/uploads/eclipse-complex/719018-complex15.zip" -o data/complex15.zip
          curl -L "https://files.gta5-mods.com/uploads/gta-iv-suffolk-church-sp-fivem/e2bc7a-MLOsuffolkchurch.rar" -o data/MLO_suffolkchurch.rar

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add downloaded GTA5-mods files" || echo "No changes"
          git push
